export default {
  CRIAR_PERSISTENCIA_DE_DADOS_NO_CADASTRO: '316',
  EDICAO_DE_INFORMACOES_PROFISSIONAIS: '323',
  EDICAO_INFO_PESSOAIS: '324',
  EXCLUSAO_USUARIO: '338',
  LINHAS_DE_CUIDADO: '365',
  DENUNCIAR: '385',
  BANNER_ASSISTENCIA_FARMACEUTICA: '401',
  CONFIRMACAO_AO_SAIR: '399',
  QUALIQUIZ: '403',
  ELMO: '411',
  VACINACOVID19: '445',
  PLANO_CONTIGENCIA: '440'
};
