export default {
  MOSTRAR_ESPECIALIDADES_NO_PERFIL: '313',
  DISPOR_FORCA_TAREFA_EM_CARROSSEL: '315',
  CRIAR_PERSISTENCIA_DE_DADOS_NO_CADASTRO: '316',
  IMPLEMENTAR_VALIDAÇÃO_CPF: '312',
  FEATURE_LOGIN_AUTOMATICO_APOS_CADASTRO: '376',
  EDICAO_DE_INFORMACOES_PROFISSIONAIS: '323',
  EXCLUSAO_USUARIO: '338',
  LINHAS_DE_CUIDADO: '365'
};
