export const labelsAnalytics = {
  HOME_BANNER_0: 'banner_vacina_covid19',
  HOME_BANNER_1: 'guia_assistencia_farmaceutica',
  HOME_BANNER_2: 'id_saude',
  SUS_NO_CEARA: 'sus_no_ceara',
  ISUS_ESP: 'isus_esp',
  ESP_SESA: 'esp_sesa',
  CARTAO_VACINA_COVID19: 'cartao_vacina_covid19',
  CARTAO_PLANO_CONTIGENCIA: 'cartao_plano_contingencia',
  ENVIAR_ALERTA_FALTA_EPI: 'enviar_alerta_falta_epi',
  ENVIAR_DEMANDA_EDUCACAO: 'enviar_demanda_educacao',
  ENVIAR_DUVIDAS_ELMO: 'enviar_duvidas_elmo',
  ENVIAR_FEEDBACK: 'enviar_feedback',
  PULAR_TUTORIAL: 'pular_tutorial',
  PROXIMO_TUTORIAL: 'proximo_tutorial',
  INICIAR_MEU_CADASTRO: 'iniciar_meu_cadastro',
  FINALIZAR_MEU_CADASTRO: 'finalizar_meu_cadastro',
  EDITAR_INFORMACOES_PROFISSIONAIS: 'editar_informacoes_profissionais',
  EDITAR_INFORMACOES_PESSOAL: 'editar_info_pessoal',
  MATERNO_INFANTIL: {
    NASCER_NO_CEARA: 'nascer_no_ceara',
    ESTRATIFICACAO_DE_RISCO: 'guias_estratificacao_risco',
    PRE_NATAL_RISCO_HABITUAL: 'guias_pre_natal_risco_habitual',
    PRE_NATAL_ALTO_RISCO: 'guias_pre_natal_alto_risco',
    SINDROMES_HIPERTENSIVAS_GESTACAO: 'guias_sindromes_hipertensivas_gestacao',
    GUIA_HEMORRAGIA_GESTACAO: 'guias_hemorragia_gestacao',
  },
  ARBOVIROSES: {
    AGENTES_COMBATE_ENDEMIAS: 'guias_agentes_combate_endemias',
    DEFINICAO_CASO_SUSPEITO_DENGUE: 'guias_def_caso_suspeito_dengue',
    DEFINICAO_CASO_SUSPEITO_CHIKUNGUNYA: 'guias_def_caso_suspeito_chikungunya',
    DEFINICAO_CASO_SUSPEITO_ZIKA: 'guias_def_caso_suspeito_zika',
    DEFINICAO_CASO_SUSPEITO_FEBRE_AMARELA:
      'guias_def_caso_suspeito_febre_amarela',
    BOLETINS_EPIDEMIOLOGICOS: 'arboviroses_link_bolet_epidemiologicos',
    VIGILANCIA_ENTOMOLOGICA: 'arboviroses_link_vigi_entomologica',
    VIGILANCIA_EPIDEMIOLOGICA: 'arboviroses_link_vigi_epidemiologica',
    DIAGNOSTICO_LAB_ARBOVIROSES: 'arboviroses_link_diag_lab_arboviroses',
    CONTROLE_VETOR: 'arboviroses_link_controle_vetor',
    MELHOR_DEFESA_PREVENCAO: 'arboviroses_link_melhor_defesa_prevencao',
    JOGO_TABULEIRO: 'arboviroses_link_jogo_tabuleiro',
    MANUAL_PROTECAO_AGENTES_ENDEMIAS: 'arboviroses_link_manual_agen_endemias',
  },
  MONKEYPOX: {
    TRATAMENTO: 'monkeypox_tratamento',
    MANIFERSTACOES_CLINICAS: 'monkeypox_manifestacoes_clinicas',
    TRANSMISSAO: 'monkeypox_transmissao',
    PREVENCAO: 'monkeypox_prevencao',
    MANEJO_CLINICO: 'monkeypox_manejo_clinico'
  }
};
