export default {
  ADICIONAR_INFORMACOES_PROFISSIONAIS_NAO_CADASTRADAS: '288',
  SECAO_CONTEUDO_HOME_PERSONALIZADA: '306',
  CRIAR_CAMPO_DE_ESPECIALIDADES: '309',
  MOSTRAR_ESPECIALIDADES_NO_PERFIL: '313',
  DISPOR_FORCA_TAREFA_EM_CARROSSEL: '315',
  CRIAR_PERSISTENCIA_DE_DADOS_NO_CADASTRO: '316',
  IMPLEMENTAR_VALIDAÇÃO_CPF: '312',
};
