export default {
  PERFIL: '134',
  DISPOR_NOSSOS_SERVICOS_EM_CARROSSEL: '302',
  ADICIONAR_INFORMACOES_PROFISSIONAIS_NAO_CADASTRADAS: '288',
  SECAO_CONTEUDO_HOME_PERSONALIZADA: '306',
  DISPOR_FORCA_TAREFA_EM_CARROSSEL: '315'
};
