import Feature from './utils/features';

export default [
  Feature.ADICIONAR_INFORMACOES_PROFISSIONAIS_NAO_CADASTRADAS,
  Feature.SECAO_CONTEUDO_HOME_PERSONALIZADA,
  Feature.DISPOR_FORCA_TAREFA_EM_CARROSSEL,
  Feature.MOSTRAR_ESPECIALIDADES_NO_PERFIL,
  Feature.CRIAR_PERSISTENCIA_DE_DADOS_NO_CADASTRO,
  Feature.IMPLEMENTAR_VALIDAÇÃO_CPF
];
