import Feature from './utils/features';

export default [
  Feature.PERFIL,
  Feature.DISPOR_NOSSOS_SERVICOS_EM_CARROSSEL,
  Feature.ADICIONAR_INFORMACOES_PROFISSIONAIS_NAO_CADASTRADAS,
  Feature.SECAO_CONTEUDO_HOME_PERSONALIZADA
];
